// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	predictorsdk "github.com/PredictorSDK/sdk-go"
	core "github.com/PredictorSDK/sdk-go/core"
	internal "github.com/PredictorSDK/sdk-go/internal"
	option "github.com/PredictorSDK/sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func New(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Find cross-platform market matches for sports events. Provide a Kalshi event ticker or Polymarket market slug to look up the equivalent market on other platforms. When called without parameters, returns all currently matched sports markets.
func (c *Client) GetSportsMatchingMarkets(
	ctx context.Context,
	request *predictorsdk.GetSportsMatchingMarketsRequest,
	opts ...option.RequestOption,
) (*predictorsdk.SportsMatchingResponse, error) {
	response, err := c.WithRawResponse.GetSportsMatchingMarkets(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
