// Code generated by Fern. DO NOT EDIT.

package predictorsdk

import (
	json "encoding/json"
	core "github.com/PredictorSDK/sdk-go/core"
)

// Upstream provider or API-key authorization dependency failed.
type BadGatewayError struct {
	*core.APIError
	Body *ErrorResponse
}

func (b *BadGatewayError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 502
	b.Body = body
	return nil
}

func (b *BadGatewayError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadGatewayError) Unwrap() error {
	return b.APIError
}

// Invalid query parameters: a `source_id` that is not `{provider}:{id}` with a matching provider, or that names a side rather than a market (`kalshi:yes`); a venue's own ID sent as `event_id`, including a Polymarket slug that matches no canonical event; an empty or comma-joined lookup value; more than 100 unique lookup identifiers; a retired parameter (its message names the replacement); a control parameter sent more than once; or an invalid flag, `limit` or `cursor`. The message quotes the offending value.
type BadRequestError struct {
	*core.APIError
	Body *ErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// `market_id` is ambiguous: it resolves to a different real market on more than one platform, so no single market can honestly be returned. Retry with `?platform=` naming one of the `candidates`, or use the composite `{platform}:{id}` form. Only bare identifiers whose shape is shared between Polymarket and Predict (numeric ids, kebab-case slugs) can produce this; composite ids, explicit `?platform=`, Kalshi tickers and SX Bet hashes never do.
type ConflictError struct {
	*core.APIError
	Body *AmbiguousIdentifierError
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	var body *AmbiguousIdentifierError
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// API key lacks the required permission
type ForbiddenError struct {
	*core.APIError
	Body *ErrorResponse
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// Resource not found.
type NotFoundError struct {
	*core.APIError
	Body *ErrorResponse
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Free tier monthly request allowance is exhausted, or the caller's paid subscription is in a payment-recovery state. This endpoint is available on every plan, so 402 never indicates a tier mismatch here.
type PaymentRequiredError struct {
	*core.APIError
	Body *PaymentRequiredErrorBody
}

func (p *PaymentRequiredError) UnmarshalJSON(data []byte) error {
	var body *PaymentRequiredErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.StatusCode = 402
	p.Body = body
	return nil
}

func (p *PaymentRequiredError) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

func (p *PaymentRequiredError) Unwrap() error {
	return p.APIError
}

// Public plan catalog is not configured
type ServiceUnavailableError struct {
	*core.APIError
	Body *ErrorResponse
}

func (s *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 503
	s.Body = body
	return nil
}

func (s *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *ServiceUnavailableError) Unwrap() error {
	return s.APIError
}

// API key exceeded its rate limit
type TooManyRequestsError struct {
	*core.APIError
	Body *ErrorResponse
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Missing or invalid API key
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorResponse
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
