// Code generated by Fern. DO NOT EDIT.

package predictorsdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/PredictorSDK/sdk-go/internal"
	big "math/big"
)

var (
	getBinanceCryptoPricesRequestFieldCurrency      = big.NewInt(1 << 0)
	getBinanceCryptoPricesRequestFieldStartTime     = big.NewInt(1 << 1)
	getBinanceCryptoPricesRequestFieldEndTime       = big.NewInt(1 << 2)
	getBinanceCryptoPricesRequestFieldLimit         = big.NewInt(1 << 3)
	getBinanceCryptoPricesRequestFieldPaginationKey = big.NewInt(1 << 4)
)

type GetBinanceCryptoPricesRequest struct {
	// Binance trading pair (e.g. `btcusdt`, `ethusdt`, `solusdt`). Must contain only alphanumeric characters (no hyphens, underscores, or other separators). Uppercase is accepted and automatically lowercased (e.g. `BTCUSDT` → `btcusdt`). Must be a valid Binance symbol; unknown symbols return `200` with an empty `prices` array.
	Currency string `json:"-" url:"currency"`
	// Start of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.
	StartTime *int64 `json:"-" url:"start_time,omitempty"`
	// End of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.
	EndTime *int64 `json:"-" url:"end_time,omitempty"`
	// Maximum number of prices to return. Defaults to 100 when a time range is present. Values above 100 are silently clamped to 100. Without a time range, this parameter is ignored — the endpoint always returns the single latest price.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Base64-encoded cursor from a previous response to fetch the next page of results.
	PaginationKey *string `json:"-" url:"pagination_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetBinanceCryptoPricesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetCurrency(currency string) {
	g.Currency = currency
	g.require(getBinanceCryptoPricesRequestFieldCurrency)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetStartTime(startTime *int64) {
	g.StartTime = startTime
	g.require(getBinanceCryptoPricesRequestFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetEndTime(endTime *int64) {
	g.EndTime = endTime
	g.require(getBinanceCryptoPricesRequestFieldEndTime)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getBinanceCryptoPricesRequestFieldLimit)
}

// SetPaginationKey sets the PaginationKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetPaginationKey(paginationKey *string) {
	g.PaginationKey = paginationKey
	g.require(getBinanceCryptoPricesRequestFieldPaginationKey)
}

var (
	getMarketsRequestFieldLimit  = big.NewInt(1 << 0)
	getMarketsRequestFieldCursor = big.NewInt(1 << 1)
)

type GetMarketsRequest struct {
	// Maximum number of markets to return per page. Range 1–100, default 25.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`).
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetMarketsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getMarketsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMarketsRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getMarketsRequestFieldCursor)
}

var (
	getSportsMatchingMarketsRequestFieldLimit                = big.NewInt(1 << 0)
	getSportsMatchingMarketsRequestFieldCursor               = big.NewInt(1 << 1)
	getSportsMatchingMarketsRequestFieldIncludeSettled       = big.NewInt(1 << 2)
	getSportsMatchingMarketsRequestFieldKalshiEventTicker    = big.NewInt(1 << 3)
	getSportsMatchingMarketsRequestFieldPolymarketMarketSlug = big.NewInt(1 << 4)
	getSportsMatchingMarketsRequestFieldPredictMarketID      = big.NewInt(1 << 5)
	getSportsMatchingMarketsRequestFieldSxbetMarketID        = big.NewInt(1 << 6)
)

type GetSportsMatchingMarketsRequest struct {
	// Maximum number of matched events to return per page. Range 1–100, default 25. Ignored when a platform-ID filter is supplied.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`). Must be used with the same filter set — a cursor from `include_settled=true` cannot be replayed against `include_settled=false` and will return `400`.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// When `true`, include settled/archived events alongside currently live matches. Defaults to `false`.
	IncludeSettled *bool `json:"-" url:"include_settled,omitempty"`
	// Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.
	KalshiEventTicker []*string `json:"-" url:"kalshi_event_ticker,omitempty"`
	// Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.
	PolymarketMarketSlug []*string `json:"-" url:"polymarket_market_slug,omitempty"`
	// Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.
	PredictMarketID []*string `json:"-" url:"predict_market_id,omitempty"`
	// SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.
	SxbetMarketID []*string `json:"-" url:"sxbet_market_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSportsMatchingMarketsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getSportsMatchingMarketsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetCursor(cursor *string) {
	g.Cursor = cursor
	g.require(getSportsMatchingMarketsRequestFieldCursor)
}

// SetIncludeSettled sets the IncludeSettled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetIncludeSettled(includeSettled *bool) {
	g.IncludeSettled = includeSettled
	g.require(getSportsMatchingMarketsRequestFieldIncludeSettled)
}

// SetKalshiEventTicker sets the KalshiEventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetKalshiEventTicker(kalshiEventTicker []*string) {
	g.KalshiEventTicker = kalshiEventTicker
	g.require(getSportsMatchingMarketsRequestFieldKalshiEventTicker)
}

// SetPolymarketMarketSlug sets the PolymarketMarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPolymarketMarketSlug(polymarketMarketSlug []*string) {
	g.PolymarketMarketSlug = polymarketMarketSlug
	g.require(getSportsMatchingMarketsRequestFieldPolymarketMarketSlug)
}

// SetPredictMarketID sets the PredictMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPredictMarketID(predictMarketID []*string) {
	g.PredictMarketID = predictMarketID
	g.require(getSportsMatchingMarketsRequestFieldPredictMarketID)
}

// SetSxbetMarketID sets the SxbetMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetSxbetMarketID(sxbetMarketID []*string) {
	g.SxbetMarketID = sxbetMarketID
	g.require(getSportsMatchingMarketsRequestFieldSxbetMarketID)
}

var (
	cryptoPriceItemFieldSymbol    = big.NewInt(1 << 0)
	cryptoPriceItemFieldValue     = big.NewInt(1 << 1)
	cryptoPriceItemFieldTimestamp = big.NewInt(1 << 2)
)

type CryptoPriceItem struct {
	// Trading pair in lowercase (e.g. `btcusdt`).
	Symbol string `json:"symbol" url:"symbol"`
	// Close price for the 1-second interval.
	Value float64 `json:"value" url:"value"`
	// Unix timestamp in milliseconds for the start of the 1-second interval.
	Timestamp int64 `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoPriceItem) GetSymbol() string {
	if c == nil {
		return ""
	}
	return c.Symbol
}

func (c *CryptoPriceItem) GetValue() float64 {
	if c == nil {
		return 0
	}
	return c.Value
}

func (c *CryptoPriceItem) GetTimestamp() int64 {
	if c == nil {
		return 0
	}
	return c.Timestamp
}

func (c *CryptoPriceItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoPriceItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(cryptoPriceItemFieldSymbol)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetValue(value float64) {
	c.Value = value
	c.require(cryptoPriceItemFieldValue)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetTimestamp(timestamp int64) {
	c.Timestamp = timestamp
	c.require(cryptoPriceItemFieldTimestamp)
}

func (c *CryptoPriceItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoPriceItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoPriceItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoPriceItem) MarshalJSON() ([]byte, error) {
	type embed CryptoPriceItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoPriceItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptoPricesResponseFieldPrices        = big.NewInt(1 << 0)
	cryptoPricesResponseFieldPaginationKey = big.NewInt(1 << 1)
	cryptoPricesResponseFieldTotal         = big.NewInt(1 << 2)
)

type CryptoPricesResponse struct {
	Prices []*CryptoPriceItem `json:"prices" url:"prices"`
	// Base64-encoded cursor for fetching the next page. Absent when there are no more results.
	PaginationKey *string `json:"pagination_key,omitempty" url:"pagination_key,omitempty"`
	// Number of prices in this response page. Omitted on empty responses for unknown symbols.
	Total *int `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoPricesResponse) GetPrices() []*CryptoPriceItem {
	if c == nil {
		return nil
	}
	return c.Prices
}

func (c *CryptoPricesResponse) GetPaginationKey() *string {
	if c == nil {
		return nil
	}
	return c.PaginationKey
}

func (c *CryptoPricesResponse) GetTotal() *int {
	if c == nil {
		return nil
	}
	return c.Total
}

func (c *CryptoPricesResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoPricesResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPrices sets the Prices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetPrices(prices []*CryptoPriceItem) {
	c.Prices = prices
	c.require(cryptoPricesResponseFieldPrices)
}

// SetPaginationKey sets the PaginationKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetPaginationKey(paginationKey *string) {
	c.PaginationKey = paginationKey
	c.require(cryptoPricesResponseFieldPaginationKey)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetTotal(total *int) {
	c.Total = total
	c.require(cryptoPricesResponseFieldTotal)
}

func (c *CryptoPricesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoPricesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoPricesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoPricesResponse) MarshalJSON() ([]byte, error) {
	type embed CryptoPricesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoPricesResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	errorResponseFieldError      = big.NewInt(1 << 0)
	errorResponseFieldMessage    = big.NewInt(1 << 1)
	errorResponseFieldStatusCode = big.NewInt(1 << 2)
)

type ErrorResponse struct {
	Error string `json:"error" url:"error"`
	// Additional detail about the error. May be present, including on some validation errors.
	Message    *string `json:"message,omitempty" url:"message,omitempty"`
	StatusCode int     `json:"status_code" url:"status_code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}

func (e *ErrorResponse) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *ErrorResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetMessage(message *string) {
	e.Message = message
	e.require(errorResponseFieldMessage)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetStatusCode(statusCode int) {
	e.StatusCode = statusCode
	e.require(errorResponseFieldStatusCode)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	marketsListResponseFieldData       = big.NewInt(1 << 0)
	marketsListResponseFieldPagination = big.NewInt(1 << 1)
)

type MarketsListResponse struct {
	// Array of markets for the current page.
	Data []*UnifiedMarket `json:"data" url:"data"`
	// Pagination metadata for the current page.
	Pagination *PaginationBlock `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MarketsListResponse) GetData() []*UnifiedMarket {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MarketsListResponse) GetPagination() *PaginationBlock {
	if m == nil {
		return nil
	}
	return m.Pagination
}

func (m *MarketsListResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MarketsListResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarketsListResponse) SetData(data []*UnifiedMarket) {
	m.Data = data
	m.require(marketsListResponseFieldData)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarketsListResponse) SetPagination(pagination *PaginationBlock) {
	m.Pagination = pagination
	m.require(marketsListResponseFieldPagination)
}

func (m *MarketsListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MarketsListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MarketsListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MarketsListResponse) MarshalJSON() ([]byte, error) {
	type embed MarketsListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MarketsListResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	paginationBlockFieldLimit      = big.NewInt(1 << 0)
	paginationBlockFieldTotal      = big.NewInt(1 << 1)
	paginationBlockFieldHasMore    = big.NewInt(1 << 2)
	paginationBlockFieldNextCursor = big.NewInt(1 << 3)
)

type PaginationBlock struct {
	// Number of items requested per page (echoes the `limit` query param).
	Limit int `json:"limit" url:"limit"`
	// Total matching items across all pages.
	Total int `json:"total" url:"total"`
	// Whether additional pages exist beyond this one.
	HasMore bool `json:"has_more" url:"has_more"`
	// Opaque cursor for fetching the next page. Pass back via the `cursor` query parameter. Omitted when `has_more` is `false`. Clients must preserve the same filter set when re-using a cursor — mismatches return `400`.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginationBlock) GetLimit() int {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PaginationBlock) GetTotal() int {
	if p == nil {
		return 0
	}
	return p.Total
}

func (p *PaginationBlock) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PaginationBlock) GetNextCursor() *string {
	if p == nil {
		return nil
	}
	return p.NextCursor
}

func (p *PaginationBlock) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginationBlock) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationBlock) SetLimit(limit int) {
	p.Limit = limit
	p.require(paginationBlockFieldLimit)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationBlock) SetTotal(total int) {
	p.Total = total
	p.require(paginationBlockFieldTotal)
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationBlock) SetHasMore(hasMore bool) {
	p.HasMore = hasMore
	p.require(paginationBlockFieldHasMore)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationBlock) SetNextCursor(nextCursor *string) {
	p.NextCursor = nextCursor
	p.require(paginationBlockFieldNextCursor)
}

func (p *PaginationBlock) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginationBlock
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginationBlock(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginationBlock) MarshalJSON() ([]byte, error) {
	type embed PaginationBlock
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginationBlock) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	platformMarketFieldPlatform      = big.NewInt(1 << 0)
	platformMarketFieldEventTicker   = big.NewInt(1 << 1)
	platformMarketFieldMarketTickers = big.NewInt(1 << 2)
	platformMarketFieldMarketSlug    = big.NewInt(1 << 3)
	platformMarketFieldTokenIDs      = big.NewInt(1 << 4)
	platformMarketFieldMarketID      = big.NewInt(1 << 5)
	platformMarketFieldOutcomeIDs    = big.NewInt(1 << 6)
)

type PlatformMarket struct {
	Platform PlatformMarketPlatform `json:"platform" url:"platform"`
	// Kalshi event ticker. Present when platform is KALSHI.
	EventTicker *string `json:"event_ticker,omitempty" url:"event_ticker,omitempty"`
	// Kalshi market tickers. Present when platform is KALSHI.
	MarketTickers []string `json:"market_tickers,omitempty" url:"market_tickers,omitempty"`
	// Polymarket market slug. Present when platform is POLYMARKET.
	MarketSlug *string `json:"market_slug,omitempty" url:"market_slug,omitempty"`
	// Polymarket token IDs. Present when platform is POLYMARKET.
	TokenIDs []string `json:"token_ids,omitempty" url:"token_ids,omitempty"`
	// Source market ID. Present for platforms other than Kalshi and Polymarket.
	MarketID *string `json:"market_id,omitempty" url:"market_id,omitempty"`
	// Source outcome IDs. Present for platforms that use outcome IDs.
	OutcomeIDs []string `json:"outcome_ids,omitempty" url:"outcome_ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlatformMarket) GetPlatform() PlatformMarketPlatform {
	if p == nil {
		return ""
	}
	return p.Platform
}

func (p *PlatformMarket) GetEventTicker() *string {
	if p == nil {
		return nil
	}
	return p.EventTicker
}

func (p *PlatformMarket) GetMarketTickers() []string {
	if p == nil {
		return nil
	}
	return p.MarketTickers
}

func (p *PlatformMarket) GetMarketSlug() *string {
	if p == nil {
		return nil
	}
	return p.MarketSlug
}

func (p *PlatformMarket) GetTokenIDs() []string {
	if p == nil {
		return nil
	}
	return p.TokenIDs
}

func (p *PlatformMarket) GetMarketID() *string {
	if p == nil {
		return nil
	}
	return p.MarketID
}

func (p *PlatformMarket) GetOutcomeIDs() []string {
	if p == nil {
		return nil
	}
	return p.OutcomeIDs
}

func (p *PlatformMarket) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlatformMarket) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetPlatform(platform PlatformMarketPlatform) {
	p.Platform = platform
	p.require(platformMarketFieldPlatform)
}

// SetEventTicker sets the EventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetEventTicker(eventTicker *string) {
	p.EventTicker = eventTicker
	p.require(platformMarketFieldEventTicker)
}

// SetMarketTickers sets the MarketTickers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketTickers(marketTickers []string) {
	p.MarketTickers = marketTickers
	p.require(platformMarketFieldMarketTickers)
}

// SetMarketSlug sets the MarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketSlug(marketSlug *string) {
	p.MarketSlug = marketSlug
	p.require(platformMarketFieldMarketSlug)
}

// SetTokenIDs sets the TokenIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetTokenIDs(tokenIDs []string) {
	p.TokenIDs = tokenIDs
	p.require(platformMarketFieldTokenIDs)
}

// SetMarketID sets the MarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketID(marketID *string) {
	p.MarketID = marketID
	p.require(platformMarketFieldMarketID)
}

// SetOutcomeIDs sets the OutcomeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetOutcomeIDs(outcomeIDs []string) {
	p.OutcomeIDs = outcomeIDs
	p.require(platformMarketFieldOutcomeIDs)
}

func (p *PlatformMarket) UnmarshalJSON(data []byte) error {
	type unmarshaler PlatformMarket
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlatformMarket(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlatformMarket) MarshalJSON() ([]byte, error) {
	type embed PlatformMarket
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlatformMarket) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlatformMarketPlatform string

const (
	PlatformMarketPlatformKalshi     PlatformMarketPlatform = "KALSHI"
	PlatformMarketPlatformPolymarket PlatformMarketPlatform = "POLYMARKET"
	PlatformMarketPlatformPredict    PlatformMarketPlatform = "PREDICT"
	PlatformMarketPlatformSxbet      PlatformMarketPlatform = "SXBET"
)

func NewPlatformMarketPlatformFromString(s string) (PlatformMarketPlatform, error) {
	switch s {
	case "KALSHI":
		return PlatformMarketPlatformKalshi, nil
	case "POLYMARKET":
		return PlatformMarketPlatformPolymarket, nil
	case "PREDICT":
		return PlatformMarketPlatformPredict, nil
	case "SXBET":
		return PlatformMarketPlatformSxbet, nil
	}
	var t PlatformMarketPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlatformMarketPlatform) Ptr() *PlatformMarketPlatform {
	return &p
}

var (
	sportsMatchingResponseFieldMarkets    = big.NewInt(1 << 0)
	sportsMatchingResponseFieldPagination = big.NewInt(1 << 1)
)

type SportsMatchingResponse struct {
	// Key-value pairs where each key is the queried identifier (Kalshi event ticker, Polymarket slug, or canonical event ID when no filter is provided) and each value is an array of platform market objects.
	Markets map[string][]*PlatformMarket `json:"markets" url:"markets"`
	// Pagination metadata for the current page. Present in list mode (no platform-ID filter). Absent in lookup mode since the response is bounded by the filter.
	Pagination *PaginationBlock `json:"pagination,omitempty" url:"pagination,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SportsMatchingResponse) GetMarkets() map[string][]*PlatformMarket {
	if s == nil {
		return nil
	}
	return s.Markets
}

func (s *SportsMatchingResponse) GetPagination() *PaginationBlock {
	if s == nil {
		return nil
	}
	return s.Pagination
}

func (s *SportsMatchingResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SportsMatchingResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMarkets sets the Markets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SportsMatchingResponse) SetMarkets(markets map[string][]*PlatformMarket) {
	s.Markets = markets
	s.require(sportsMatchingResponseFieldMarkets)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SportsMatchingResponse) SetPagination(pagination *PaginationBlock) {
	s.Pagination = pagination
	s.require(sportsMatchingResponseFieldPagination)
}

func (s *SportsMatchingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SportsMatchingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SportsMatchingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SportsMatchingResponse) MarshalJSON() ([]byte, error) {
	type embed SportsMatchingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SportsMatchingResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	unifiedMarketFieldID       = big.NewInt(1 << 0)
	unifiedMarketFieldProvider = big.NewInt(1 << 1)
	unifiedMarketFieldTitle    = big.NewInt(1 << 2)
)

type UnifiedMarket struct {
	// Composite market identifier in the format `{provider}:{provider_id}` (e.g. `kalshi:KXNBAGAME-26MAR06INDLAL-LAL`).
	ID string `json:"id" url:"id"`
	// Prediction market provider.
	Provider UnifiedMarketProvider `json:"provider" url:"provider"`
	// Human-readable market title/question.
	Title string `json:"title" url:"title"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnifiedMarket) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UnifiedMarket) GetProvider() UnifiedMarketProvider {
	if u == nil {
		return ""
	}
	return u.Provider
}

func (u *UnifiedMarket) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

func (u *UnifiedMarket) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnifiedMarket) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnifiedMarket) SetID(id string) {
	u.ID = id
	u.require(unifiedMarketFieldID)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnifiedMarket) SetProvider(provider UnifiedMarketProvider) {
	u.Provider = provider
	u.require(unifiedMarketFieldProvider)
}

// SetTitle sets the Title field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnifiedMarket) SetTitle(title string) {
	u.Title = title
	u.require(unifiedMarketFieldTitle)
}

func (u *UnifiedMarket) UnmarshalJSON(data []byte) error {
	type unmarshaler UnifiedMarket
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnifiedMarket(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnifiedMarket) MarshalJSON() ([]byte, error) {
	type embed UnifiedMarket
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnifiedMarket) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Prediction market provider.
type UnifiedMarketProvider string

const (
	UnifiedMarketProviderKalshi     UnifiedMarketProvider = "kalshi"
	UnifiedMarketProviderPolymarket UnifiedMarketProvider = "polymarket"
	UnifiedMarketProviderPredict    UnifiedMarketProvider = "predict"
	UnifiedMarketProviderSxbet      UnifiedMarketProvider = "sxbet"
)

func NewUnifiedMarketProviderFromString(s string) (UnifiedMarketProvider, error) {
	switch s {
	case "kalshi":
		return UnifiedMarketProviderKalshi, nil
	case "polymarket":
		return UnifiedMarketProviderPolymarket, nil
	case "predict":
		return UnifiedMarketProviderPredict, nil
	case "sxbet":
		return UnifiedMarketProviderSxbet, nil
	}
	var t UnifiedMarketProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UnifiedMarketProvider) Ptr() *UnifiedMarketProvider {
	return &u
}
