// Code generated by Fern. DO NOT EDIT.

package predictorsdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/PredictorSDK/sdk-go/internal"
	big "math/big"
)

var (
	getSportsMatchingMarketsRequestFieldKalshiEventTicker    = big.NewInt(1 << 0)
	getSportsMatchingMarketsRequestFieldPolymarketMarketSlug = big.NewInt(1 << 1)
	getSportsMatchingMarketsRequestFieldPredictMarketID      = big.NewInt(1 << 2)
	getSportsMatchingMarketsRequestFieldSxbetMarketID        = big.NewInt(1 << 3)
)

type GetSportsMatchingMarketsRequest struct {
	// Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request.
	KalshiEventTicker []*string `json:"-" url:"kalshi_event_ticker,omitempty"`
	// Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request.
	PolymarketMarketSlug []*string `json:"-" url:"polymarket_market_slug,omitempty"`
	// Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.
	PredictMarketID []*string `json:"-" url:"predict_market_id,omitempty"`
	// SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.
	SxbetMarketID []*string `json:"-" url:"sxbet_market_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSportsMatchingMarketsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKalshiEventTicker sets the KalshiEventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetKalshiEventTicker(kalshiEventTicker []*string) {
	g.KalshiEventTicker = kalshiEventTicker
	g.require(getSportsMatchingMarketsRequestFieldKalshiEventTicker)
}

// SetPolymarketMarketSlug sets the PolymarketMarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPolymarketMarketSlug(polymarketMarketSlug []*string) {
	g.PolymarketMarketSlug = polymarketMarketSlug
	g.require(getSportsMatchingMarketsRequestFieldPolymarketMarketSlug)
}

// SetPredictMarketID sets the PredictMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPredictMarketID(predictMarketID []*string) {
	g.PredictMarketID = predictMarketID
	g.require(getSportsMatchingMarketsRequestFieldPredictMarketID)
}

// SetSxbetMarketID sets the SxbetMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetSxbetMarketID(sxbetMarketID []*string) {
	g.SxbetMarketID = sxbetMarketID
	g.require(getSportsMatchingMarketsRequestFieldSxbetMarketID)
}

var (
	errorResponseFieldError      = big.NewInt(1 << 0)
	errorResponseFieldStatusCode = big.NewInt(1 << 1)
)

type ErrorResponse struct {
	Error      string `json:"error" url:"error"`
	StatusCode int    `json:"status_code" url:"status_code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}

func (e *ErrorResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetStatusCode(statusCode int) {
	e.StatusCode = statusCode
	e.require(errorResponseFieldStatusCode)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	platformMarketFieldPlatform      = big.NewInt(1 << 0)
	platformMarketFieldEventTicker   = big.NewInt(1 << 1)
	platformMarketFieldMarketTickers = big.NewInt(1 << 2)
	platformMarketFieldMarketSlug    = big.NewInt(1 << 3)
	platformMarketFieldTokenIDs      = big.NewInt(1 << 4)
	platformMarketFieldMarketID      = big.NewInt(1 << 5)
	platformMarketFieldOutcomeIDs    = big.NewInt(1 << 6)
)

type PlatformMarket struct {
	Platform PlatformMarketPlatform `json:"platform" url:"platform"`
	// Kalshi event ticker. Present when platform is KALSHI.
	EventTicker *string `json:"event_ticker,omitempty" url:"event_ticker,omitempty"`
	// Kalshi market tickers. Present when platform is KALSHI.
	MarketTickers []string `json:"market_tickers,omitempty" url:"market_tickers,omitempty"`
	// Polymarket market slug. Present when platform is POLYMARKET.
	MarketSlug *string `json:"market_slug,omitempty" url:"market_slug,omitempty"`
	// Polymarket token IDs. Present when platform is POLYMARKET.
	TokenIDs []string `json:"token_ids,omitempty" url:"token_ids,omitempty"`
	// Source market ID. Present for platforms other than Kalshi and Polymarket.
	MarketID *string `json:"market_id,omitempty" url:"market_id,omitempty"`
	// Source outcome IDs. Present for platforms that use outcome IDs.
	OutcomeIDs []string `json:"outcome_ids,omitempty" url:"outcome_ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlatformMarket) GetPlatform() PlatformMarketPlatform {
	if p == nil {
		return ""
	}
	return p.Platform
}

func (p *PlatformMarket) GetEventTicker() *string {
	if p == nil {
		return nil
	}
	return p.EventTicker
}

func (p *PlatformMarket) GetMarketTickers() []string {
	if p == nil {
		return nil
	}
	return p.MarketTickers
}

func (p *PlatformMarket) GetMarketSlug() *string {
	if p == nil {
		return nil
	}
	return p.MarketSlug
}

func (p *PlatformMarket) GetTokenIDs() []string {
	if p == nil {
		return nil
	}
	return p.TokenIDs
}

func (p *PlatformMarket) GetMarketID() *string {
	if p == nil {
		return nil
	}
	return p.MarketID
}

func (p *PlatformMarket) GetOutcomeIDs() []string {
	if p == nil {
		return nil
	}
	return p.OutcomeIDs
}

func (p *PlatformMarket) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlatformMarket) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetPlatform(platform PlatformMarketPlatform) {
	p.Platform = platform
	p.require(platformMarketFieldPlatform)
}

// SetEventTicker sets the EventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetEventTicker(eventTicker *string) {
	p.EventTicker = eventTicker
	p.require(platformMarketFieldEventTicker)
}

// SetMarketTickers sets the MarketTickers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketTickers(marketTickers []string) {
	p.MarketTickers = marketTickers
	p.require(platformMarketFieldMarketTickers)
}

// SetMarketSlug sets the MarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketSlug(marketSlug *string) {
	p.MarketSlug = marketSlug
	p.require(platformMarketFieldMarketSlug)
}

// SetTokenIDs sets the TokenIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetTokenIDs(tokenIDs []string) {
	p.TokenIDs = tokenIDs
	p.require(platformMarketFieldTokenIDs)
}

// SetMarketID sets the MarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketID(marketID *string) {
	p.MarketID = marketID
	p.require(platformMarketFieldMarketID)
}

// SetOutcomeIDs sets the OutcomeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetOutcomeIDs(outcomeIDs []string) {
	p.OutcomeIDs = outcomeIDs
	p.require(platformMarketFieldOutcomeIDs)
}

func (p *PlatformMarket) UnmarshalJSON(data []byte) error {
	type unmarshaler PlatformMarket
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlatformMarket(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlatformMarket) MarshalJSON() ([]byte, error) {
	type embed PlatformMarket
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlatformMarket) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlatformMarketPlatform string

const (
	PlatformMarketPlatformKalshi     PlatformMarketPlatform = "KALSHI"
	PlatformMarketPlatformPolymarket PlatformMarketPlatform = "POLYMARKET"
	PlatformMarketPlatformPredict    PlatformMarketPlatform = "PREDICT"
	PlatformMarketPlatformSxbet      PlatformMarketPlatform = "SXBET"
)

func NewPlatformMarketPlatformFromString(s string) (PlatformMarketPlatform, error) {
	switch s {
	case "KALSHI":
		return PlatformMarketPlatformKalshi, nil
	case "POLYMARKET":
		return PlatformMarketPlatformPolymarket, nil
	case "PREDICT":
		return PlatformMarketPlatformPredict, nil
	case "SXBET":
		return PlatformMarketPlatformSxbet, nil
	}
	var t PlatformMarketPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlatformMarketPlatform) Ptr() *PlatformMarketPlatform {
	return &p
}

var (
	sportsMatchingResponseFieldMarkets = big.NewInt(1 << 0)
)

type SportsMatchingResponse struct {
	// Key-value pairs where each key is the queried identifier (Kalshi event ticker, Polymarket slug, or canonical event ID when no filter is provided) and each value is an array of platform market objects.
	Markets map[string][]*PlatformMarket `json:"markets" url:"markets"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SportsMatchingResponse) GetMarkets() map[string][]*PlatformMarket {
	if s == nil {
		return nil
	}
	return s.Markets
}

func (s *SportsMatchingResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SportsMatchingResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMarkets sets the Markets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SportsMatchingResponse) SetMarkets(markets map[string][]*PlatformMarket) {
	s.Markets = markets
	s.require(sportsMatchingResponseFieldMarkets)
}

func (s *SportsMatchingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SportsMatchingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SportsMatchingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SportsMatchingResponse) MarshalJSON() ([]byte, error) {
	type embed SportsMatchingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SportsMatchingResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
