// Code generated by Fern. DO NOT EDIT.

package predictorsdk

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/PredictorSDK/sdk-go/internal"
	big "math/big"
)

var (
	getBinanceCryptoPricesRequestFieldCurrency      = big.NewInt(1 << 0)
	getBinanceCryptoPricesRequestFieldStartTime     = big.NewInt(1 << 1)
	getBinanceCryptoPricesRequestFieldEndTime       = big.NewInt(1 << 2)
	getBinanceCryptoPricesRequestFieldLimit         = big.NewInt(1 << 3)
	getBinanceCryptoPricesRequestFieldPaginationKey = big.NewInt(1 << 4)
)

type GetBinanceCryptoPricesRequest struct {
	// Binance trading pair (e.g. `btcusdt`, `ethusdt`, `solusdt`). Must contain only alphanumeric characters (no hyphens, underscores, or other separators). Uppercase is accepted and automatically lowercased (e.g. `BTCUSDT` → `btcusdt`). Must be a valid Binance symbol; unknown symbols return `200` with an empty `prices` array.
	Currency string `json:"-" url:"currency"`
	// Start of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.
	StartTime *int64 `json:"-" url:"start_time,omitempty"`
	// End of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.
	EndTime *int64 `json:"-" url:"end_time,omitempty"`
	// Maximum number of prices to return. Defaults to 100 when a time range is present. Values above 100 are silently clamped to 100. Without a time range, this parameter is ignored — the endpoint always returns the single latest price.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Base64-encoded cursor from a previous response to fetch the next page of results.
	PaginationKey *string `json:"-" url:"pagination_key,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetBinanceCryptoPricesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetCurrency(currency string) {
	g.Currency = currency
	g.require(getBinanceCryptoPricesRequestFieldCurrency)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetStartTime(startTime *int64) {
	g.StartTime = startTime
	g.require(getBinanceCryptoPricesRequestFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetEndTime(endTime *int64) {
	g.EndTime = endTime
	g.require(getBinanceCryptoPricesRequestFieldEndTime)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getBinanceCryptoPricesRequestFieldLimit)
}

// SetPaginationKey sets the PaginationKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBinanceCryptoPricesRequest) SetPaginationKey(paginationKey *string) {
	g.PaginationKey = paginationKey
	g.require(getBinanceCryptoPricesRequestFieldPaginationKey)
}

var (
	getSportsMatchingMarketsRequestFieldKalshiEventTicker    = big.NewInt(1 << 0)
	getSportsMatchingMarketsRequestFieldPolymarketMarketSlug = big.NewInt(1 << 1)
	getSportsMatchingMarketsRequestFieldPredictMarketID      = big.NewInt(1 << 2)
	getSportsMatchingMarketsRequestFieldSxbetMarketID        = big.NewInt(1 << 3)
)

type GetSportsMatchingMarketsRequest struct {
	// Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request.
	KalshiEventTicker []*string `json:"-" url:"kalshi_event_ticker,omitempty"`
	// Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request.
	PolymarketMarketSlug []*string `json:"-" url:"polymarket_market_slug,omitempty"`
	// Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.
	PredictMarketID []*string `json:"-" url:"predict_market_id,omitempty"`
	// SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.
	SxbetMarketID []*string `json:"-" url:"sxbet_market_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSportsMatchingMarketsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetKalshiEventTicker sets the KalshiEventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetKalshiEventTicker(kalshiEventTicker []*string) {
	g.KalshiEventTicker = kalshiEventTicker
	g.require(getSportsMatchingMarketsRequestFieldKalshiEventTicker)
}

// SetPolymarketMarketSlug sets the PolymarketMarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPolymarketMarketSlug(polymarketMarketSlug []*string) {
	g.PolymarketMarketSlug = polymarketMarketSlug
	g.require(getSportsMatchingMarketsRequestFieldPolymarketMarketSlug)
}

// SetPredictMarketID sets the PredictMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetPredictMarketID(predictMarketID []*string) {
	g.PredictMarketID = predictMarketID
	g.require(getSportsMatchingMarketsRequestFieldPredictMarketID)
}

// SetSxbetMarketID sets the SxbetMarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSportsMatchingMarketsRequest) SetSxbetMarketID(sxbetMarketID []*string) {
	g.SxbetMarketID = sxbetMarketID
	g.require(getSportsMatchingMarketsRequestFieldSxbetMarketID)
}

var (
	cryptoPriceItemFieldSymbol    = big.NewInt(1 << 0)
	cryptoPriceItemFieldValue     = big.NewInt(1 << 1)
	cryptoPriceItemFieldTimestamp = big.NewInt(1 << 2)
)

type CryptoPriceItem struct {
	// Trading pair in lowercase (e.g. `btcusdt`).
	Symbol string `json:"symbol" url:"symbol"`
	// Close price for the 1-second interval.
	Value float64 `json:"value" url:"value"`
	// Unix timestamp in milliseconds for the start of the 1-second interval.
	Timestamp int64 `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoPriceItem) GetSymbol() string {
	if c == nil {
		return ""
	}
	return c.Symbol
}

func (c *CryptoPriceItem) GetValue() float64 {
	if c == nil {
		return 0
	}
	return c.Value
}

func (c *CryptoPriceItem) GetTimestamp() int64 {
	if c == nil {
		return 0
	}
	return c.Timestamp
}

func (c *CryptoPriceItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoPriceItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSymbol sets the Symbol field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetSymbol(symbol string) {
	c.Symbol = symbol
	c.require(cryptoPriceItemFieldSymbol)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetValue(value float64) {
	c.Value = value
	c.require(cryptoPriceItemFieldValue)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPriceItem) SetTimestamp(timestamp int64) {
	c.Timestamp = timestamp
	c.require(cryptoPriceItemFieldTimestamp)
}

func (c *CryptoPriceItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoPriceItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoPriceItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoPriceItem) MarshalJSON() ([]byte, error) {
	type embed CryptoPriceItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoPriceItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	cryptoPricesResponseFieldPrices        = big.NewInt(1 << 0)
	cryptoPricesResponseFieldPaginationKey = big.NewInt(1 << 1)
	cryptoPricesResponseFieldTotal         = big.NewInt(1 << 2)
)

type CryptoPricesResponse struct {
	Prices []*CryptoPriceItem `json:"prices" url:"prices"`
	// Base64-encoded cursor for fetching the next page. Absent when there are no more results.
	PaginationKey *string `json:"pagination_key,omitempty" url:"pagination_key,omitempty"`
	// Number of prices in this response page. Omitted on empty responses for unknown symbols.
	Total *int `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CryptoPricesResponse) GetPrices() []*CryptoPriceItem {
	if c == nil {
		return nil
	}
	return c.Prices
}

func (c *CryptoPricesResponse) GetPaginationKey() *string {
	if c == nil {
		return nil
	}
	return c.PaginationKey
}

func (c *CryptoPricesResponse) GetTotal() *int {
	if c == nil {
		return nil
	}
	return c.Total
}

func (c *CryptoPricesResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CryptoPricesResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPrices sets the Prices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetPrices(prices []*CryptoPriceItem) {
	c.Prices = prices
	c.require(cryptoPricesResponseFieldPrices)
}

// SetPaginationKey sets the PaginationKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetPaginationKey(paginationKey *string) {
	c.PaginationKey = paginationKey
	c.require(cryptoPricesResponseFieldPaginationKey)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CryptoPricesResponse) SetTotal(total *int) {
	c.Total = total
	c.require(cryptoPricesResponseFieldTotal)
}

func (c *CryptoPricesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CryptoPricesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CryptoPricesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CryptoPricesResponse) MarshalJSON() ([]byte, error) {
	type embed CryptoPricesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CryptoPricesResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	errorResponseFieldError      = big.NewInt(1 << 0)
	errorResponseFieldMessage    = big.NewInt(1 << 1)
	errorResponseFieldStatusCode = big.NewInt(1 << 2)
)

type ErrorResponse struct {
	Error string `json:"error" url:"error"`
	// Additional detail about the error. May be present, including on some validation errors.
	Message    *string `json:"message,omitempty" url:"message,omitempty"`
	StatusCode int     `json:"status_code" url:"status_code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}

func (e *ErrorResponse) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *ErrorResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetMessage(message *string) {
	e.Message = message
	e.require(errorResponseFieldMessage)
}

// SetStatusCode sets the StatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetStatusCode(statusCode int) {
	e.StatusCode = statusCode
	e.require(errorResponseFieldStatusCode)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	platformMarketFieldPlatform      = big.NewInt(1 << 0)
	platformMarketFieldEventTicker   = big.NewInt(1 << 1)
	platformMarketFieldMarketTickers = big.NewInt(1 << 2)
	platformMarketFieldMarketSlug    = big.NewInt(1 << 3)
	platformMarketFieldTokenIDs      = big.NewInt(1 << 4)
	platformMarketFieldMarketID      = big.NewInt(1 << 5)
	platformMarketFieldOutcomeIDs    = big.NewInt(1 << 6)
)

type PlatformMarket struct {
	Platform PlatformMarketPlatform `json:"platform" url:"platform"`
	// Kalshi event ticker. Present when platform is KALSHI.
	EventTicker *string `json:"event_ticker,omitempty" url:"event_ticker,omitempty"`
	// Kalshi market tickers. Present when platform is KALSHI.
	MarketTickers []string `json:"market_tickers,omitempty" url:"market_tickers,omitempty"`
	// Polymarket market slug. Present when platform is POLYMARKET.
	MarketSlug *string `json:"market_slug,omitempty" url:"market_slug,omitempty"`
	// Polymarket token IDs. Present when platform is POLYMARKET.
	TokenIDs []string `json:"token_ids,omitempty" url:"token_ids,omitempty"`
	// Source market ID. Present for platforms other than Kalshi and Polymarket.
	MarketID *string `json:"market_id,omitempty" url:"market_id,omitempty"`
	// Source outcome IDs. Present for platforms that use outcome IDs.
	OutcomeIDs []string `json:"outcome_ids,omitempty" url:"outcome_ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlatformMarket) GetPlatform() PlatformMarketPlatform {
	if p == nil {
		return ""
	}
	return p.Platform
}

func (p *PlatformMarket) GetEventTicker() *string {
	if p == nil {
		return nil
	}
	return p.EventTicker
}

func (p *PlatformMarket) GetMarketTickers() []string {
	if p == nil {
		return nil
	}
	return p.MarketTickers
}

func (p *PlatformMarket) GetMarketSlug() *string {
	if p == nil {
		return nil
	}
	return p.MarketSlug
}

func (p *PlatformMarket) GetTokenIDs() []string {
	if p == nil {
		return nil
	}
	return p.TokenIDs
}

func (p *PlatformMarket) GetMarketID() *string {
	if p == nil {
		return nil
	}
	return p.MarketID
}

func (p *PlatformMarket) GetOutcomeIDs() []string {
	if p == nil {
		return nil
	}
	return p.OutcomeIDs
}

func (p *PlatformMarket) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlatformMarket) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetPlatform(platform PlatformMarketPlatform) {
	p.Platform = platform
	p.require(platformMarketFieldPlatform)
}

// SetEventTicker sets the EventTicker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetEventTicker(eventTicker *string) {
	p.EventTicker = eventTicker
	p.require(platformMarketFieldEventTicker)
}

// SetMarketTickers sets the MarketTickers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketTickers(marketTickers []string) {
	p.MarketTickers = marketTickers
	p.require(platformMarketFieldMarketTickers)
}

// SetMarketSlug sets the MarketSlug field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketSlug(marketSlug *string) {
	p.MarketSlug = marketSlug
	p.require(platformMarketFieldMarketSlug)
}

// SetTokenIDs sets the TokenIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetTokenIDs(tokenIDs []string) {
	p.TokenIDs = tokenIDs
	p.require(platformMarketFieldTokenIDs)
}

// SetMarketID sets the MarketID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetMarketID(marketID *string) {
	p.MarketID = marketID
	p.require(platformMarketFieldMarketID)
}

// SetOutcomeIDs sets the OutcomeIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlatformMarket) SetOutcomeIDs(outcomeIDs []string) {
	p.OutcomeIDs = outcomeIDs
	p.require(platformMarketFieldOutcomeIDs)
}

func (p *PlatformMarket) UnmarshalJSON(data []byte) error {
	type unmarshaler PlatformMarket
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlatformMarket(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlatformMarket) MarshalJSON() ([]byte, error) {
	type embed PlatformMarket
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlatformMarket) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlatformMarketPlatform string

const (
	PlatformMarketPlatformKalshi     PlatformMarketPlatform = "KALSHI"
	PlatformMarketPlatformPolymarket PlatformMarketPlatform = "POLYMARKET"
	PlatformMarketPlatformPredict    PlatformMarketPlatform = "PREDICT"
	PlatformMarketPlatformSxbet      PlatformMarketPlatform = "SXBET"
)

func NewPlatformMarketPlatformFromString(s string) (PlatformMarketPlatform, error) {
	switch s {
	case "KALSHI":
		return PlatformMarketPlatformKalshi, nil
	case "POLYMARKET":
		return PlatformMarketPlatformPolymarket, nil
	case "PREDICT":
		return PlatformMarketPlatformPredict, nil
	case "SXBET":
		return PlatformMarketPlatformSxbet, nil
	}
	var t PlatformMarketPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlatformMarketPlatform) Ptr() *PlatformMarketPlatform {
	return &p
}

var (
	sportsMatchingResponseFieldMarkets = big.NewInt(1 << 0)
)

type SportsMatchingResponse struct {
	// Key-value pairs where each key is the queried identifier (Kalshi event ticker, Polymarket slug, or canonical event ID when no filter is provided) and each value is an array of platform market objects.
	Markets map[string][]*PlatformMarket `json:"markets" url:"markets"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SportsMatchingResponse) GetMarkets() map[string][]*PlatformMarket {
	if s == nil {
		return nil
	}
	return s.Markets
}

func (s *SportsMatchingResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SportsMatchingResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMarkets sets the Markets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SportsMatchingResponse) SetMarkets(markets map[string][]*PlatformMarket) {
	s.Markets = markets
	s.require(sportsMatchingResponseFieldMarkets)
}

func (s *SportsMatchingResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SportsMatchingResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SportsMatchingResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SportsMatchingResponse) MarshalJSON() ([]byte, error) {
	type embed SportsMatchingResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SportsMatchingResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
